// ===================================
// Main.cpp file generated by OptFrame
// Project ODBFT
// ===================================

#include <stdlib.h>
#include <math.h>
#include <iostream>

#include "../OptFrame/Util/RandGenMersenneTwister.hpp"

#include "../OptFrame/Util/CheckCommand.hpp"

#include "ODBFT.h"

using namespace std;
using namespace optframe;
using namespace ODBFT;

int main(int argc, char **argv)
{
   RandGenMersenneTwister rg; // not using system rand() anymore
   
   // Initialize here all your OptFrame components 
   // (ProblemInstance, Evaluator, Constructive, ...)
   
   Scanner scanner("");
   ProblemInstance p(scanner);

   MyEvaluator ev(p);

   NSSeqChangeNode ns1(p, rg);
   
   ConstructiveRandom c1(p);
   
   CheckCommand<RepODBFT> check;
   check.add(ev);
   check.add(c1);
   check.add(ns1);
   
   check.run(10,10);

   cout << "Program ended successfully" << endl;
   
   return 0;
}
